'use client';
import { useEffect, useMemo, useState } from 'react';
import { Button, Card, Checkbox, Input, Modal, Select, Tag, Typography, message } from 'antd';
import { PlusOutlined, ShoppingCartOutlined } from '@ant-design/icons';
import { createClient } from '@/lib/supabase';
export default function ListsPage(){const [lists,setLists]=useState<any[]>([]),[active,setActive]=useState<any>(),[items,setItems]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[open,setOpen]=useState(false),[name,setName]=useState(''),[selected,setSelected]=useState<string>(),[qty,setQty]=useState(1);
const load=async()=>{const s=createClient();const {data}=await s.from('shopping_lists').select('*').order('updated_at',{ascending:false});setLists(data??[])};useEffect(()=>{load();(async()=>{const s=createClient();const {data}=await s.from('product_variants').select('id,variant_name_ar,variant_name_en,amount,unit').order('variant_name_ar').limit(500);setProducts(data??[])})()},[]);
const select=async(l:any)=>{setActive(l);const s=createClient();const {data}=await s.from('shopping_list_items').select('id,custom_name,requested_quantity,purchased,unit_price,total_price,product_variants(variant_name_ar,variant_name_en,amount,unit)').eq('list_id',l.id);setItems(data??[])};
const add=async()=>{if(!name.trim())return;const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){message.info('سجّل الدخول أولاً');return}const {error}=await s.from('shopping_lists').insert({user_id:user.id,name:name.trim()});if(error)message.error(error.message);else{setName('');setOpen(false);load()}};
const addItem=async()=>{if(!active||!selected)return;const s=createClient();const {error}=await s.from('shopping_list_items').insert({list_id:active.id,product_variant_id:selected,requested_quantity:qty});if(error)message.error(error.message);else{message.success('تمت الإضافة');select(active);setSelected(undefined);setQty(1)}};
const toggle=async(i:any)=>{const s=createClient();await s.from('shopping_list_items').update({purchased:!i.purchased}).eq('id',i.id);if(active)select(active)};
const startShopping=async()=>{if(!active)return;const s=createClient();await s.from('shopping_lists').update({status:'shopping'}).eq('id',active.id);setActive({...active,status:'shopping'});message.success('بدأنا التسوق 🛒')};
const options=useMemo(()=>products.map(p=>({value:p.id,label:`${p.variant_name_ar||p.variant_name_en} — ${p.amount} ${p.unit}`})),[products]);
return <main className="baytna-page"><div className="baytna-container"><section className="hero"><h1>قوائم المشتريات</h1><p>اعمل الليستة، وبعدها ابدأ التسوق وسجل اللي اشتريته.</p></section><div style={{display:'grid',gridTemplateColumns:'minmax(260px,.8fr) minmax(320px,1.5fr)',gap:16}}><Card title="قوائمك" extra={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>جديدة</Button>}>{lists.map(l=><div key={l.id} className="list-row" onClick={()=>select(l)} style={{cursor:'pointer'}}><span>{l.name}</span><Tag color={l.status==='shopping'?'orange':'green'}>{l.status}</Tag></div>)}{!lists.length&&<Typography.Text type="secondary">مفيش قوائم لسه.</Typography.Text>}</Card><Card title={active?.name||'اختار قائمة'} extra={active&&<Button icon={<ShoppingCartOutlined/>} onClick={startShopping}>ابدأ التسوق</Button>}>{active&&<div style={{display:'flex',gap:8,marginBottom:14}}><Select showSearch optionFilterProp="label" style={{flex:1}} placeholder="ابحث عن منتج" options={options} value={selected} onChange={setSelected}/><Input type="number" min={1} style={{width:90}} value={qty} onChange={e=>setQty(Number(e.target.value)||1)}/><Button type="primary" icon={<PlusOutlined/>} onClick={addItem}>إضافة</Button></div>}{active&&items.map(i=><div className="list-row" key={i.id}><Checkbox checked={i.purchased} onChange={()=>toggle(i)}><span style={{textDecoration:i.purchased?'line-through':'none'}}>{i.custom_name||i.product_variants?.variant_name_ar}</span></Checkbox><span>{i.requested_quantity} {i.product_variants?.unit}</span></div>)}{active&&!items.length&&<Typography.Text type="secondary">القائمة فاضية — اختار منتج وأضفه.</Typography.Text>}</Card></div></div><Modal title="قائمة جديدة" open={open} onCancel={()=>setOpen(false)} onOk={add} okText="إنشاء" cancelText="إلغاء"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="مشتريات الأسبوع"/></Modal></main>}
